name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [amd64, 386, arm, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Build
        run: |
          GOOS=${{ matrix.os == 'windows-latest' && 'windows' || (matrix.os == 'ubuntu-latest' && 'linux' || 'darwin') }}
          GOARCH=${{ matrix.arch }}
          OUTPUT_NAME=certshield-${{ matrix.os }}-${{ matrix.arch }}
          go build -o $OUTPUT_NAME
        env:
          CGO_ENABLED: 0

      - name: Archive build artifacts (tar.gz)
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' }}
        run: |
          tar czf certshield-${{ matrix.os }}-${{ matrix.arch }}.tar.gz certshield-${{ matrix.os }}-${{ matrix.arch }}

      - name: Archive build artifacts (zip)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          zip certshield-${{ matrix.os }}-${{ matrix.arch }}.zip certshield-${{ matrix.os }}-${{ matrix.arch }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: certshield-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            certshield-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
            certshield-${{ matrix.os }}-${{ matrix.arch }}.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Changelogithub
        run: npm install -g changelogithub

      - name: Generate Changelog
        run: changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.generate_changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: |
            certshield-ubuntu-latest-amd64.tar.gz
            certshield-ubuntu-latest-386.tar.gz
            certshield-ubuntu-latest-arm.tar.gz
            certshield-ubuntu-latest-arm64.tar.gz
            certshield-macos-latest-amd64.tar.gz
            certshield-macos-latest-386.tar.gz
            certshield-macos-latest-arm.tar.gz
            certshield-macos-latest-arm64.tar.gz
            certshield-windows-latest-amd64.zip
            certshield-windows-latest-386.zip
            certshield-windows-latest-arm.zip
            certshield-windows-latest-arm64.zip
          asset_name: ${{ matrix.os }}-${{ matrix.arch }}.${{ github.sha }}.${{ matrix.os == 'windows-latest' && 'zip' || 'tar.gz' }}
          asset_content_type: ${{ matrix.os == 'windows-latest' && 'application/zip' || 'application/gzip' }}
